package vista;

import controlador.ControladorUsuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import modelo.Usuario;

public class FrmLogin extends javax.swing.JFrame {

    int xMause, yMause;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    public FrmLogin() {
        initComponents();
        this.setResizable(false);//para evitar que el usuario pueda cambiar el tamaño de la ventana.
        this.setLocationRelativeTo(null);//para centrar la ventana en la pantalla cuando se muestra.
        this.setTitle("Login - RETELL");//para establecer el título de la ventana, es decir, el texto que aparece en la barra superior de la ventana cuando se muestra en el sistema operativo.
        this.setSize(new Dimension(700, 500));

    }
    @Override
    public Image getIconImage(){
        Image retValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/logoRetell..png"));
        return retValue.getScaledInstance(2000, 2000, Image.SCALE_SMOOTH);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usuarioTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        contrasenaTxt = new javax.swing.JPasswordField();
        ingresar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Condensed ExtraLight", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RETELL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 150, 40));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed ExtraLight", 0, 12)); // NOI18N
        jLabel1.setText("© Wilson Elias Carreño Morantes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/accesoLogin.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 250, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 500));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfildelusuario.png"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 120, 120));

        jLabel4.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USUARIO");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 51));
        jLabel7.setText("INICIO DE SESÍON");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        usuarioTxt.setBackground(new java.awt.Color(102, 102, 102));
        usuarioTxt.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        usuarioTxt.setForeground(new java.awt.Color(153, 153, 153));
        usuarioTxt.setText("Ingrese su nombre de usuario");
        usuarioTxt.setToolTipText("");
        usuarioTxt.setBorder(null);
        usuarioTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioTxtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuarioTxtMousePressed(evt);
            }
        });
        usuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTxtActionPerformed(evt);
            }
        });
        usuarioTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioTxtKeyPressed(evt);
            }
        });
        jPanel2.add(usuarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 280, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 280, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONTRASEÑA");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 280, -1));

        contrasenaTxt.setBackground(new java.awt.Color(102, 102, 102));
        contrasenaTxt.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        contrasenaTxt.setForeground(new java.awt.Color(153, 153, 153));
        contrasenaTxt.setText("....");
        contrasenaTxt.setBorder(null);
        contrasenaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contrasenaTxtMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contrasenaTxtMousePressed(evt);
            }
        });
        contrasenaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaTxtActionPerformed(evt);
            }
        });
        contrasenaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contrasenaTxtKeyPressed(evt);
            }
        });
        jPanel2.add(contrasenaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 290, -1));

        ingresar.setBackground(new java.awt.Color(51, 51, 51));
        ingresar.setForeground(new java.awt.Color(51, 51, 51));
        ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresarMouseExited(evt);
            }
        });
        ingresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Condensed ExtraLight", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingresar");
        ingresar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cohete...png"))); // NOI18N
        ingresar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jPanel2.add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 110, 40));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setFont(new java.awt.Font("Roboto Condensed Light", 0, 24)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("X");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });
        jPanel5.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 30, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, 0, 700, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 350, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTxtActionPerformed

    private void usuarioTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioTxtMousePressed
        // Solo borra si es exactamente el placeholder
        if (usuarioTxt.getText().equals("Ingrese su nombre de usuario")) {
            usuarioTxt.setText("");
            usuarioTxt.setForeground(Color.black);
        }
        if (String.valueOf(contrasenaTxt.getPassword()).isEmpty()) {
            contrasenaTxt.setText("....");
            contrasenaTxt.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_usuarioTxtMousePressed

    private void contrasenaTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenaTxtMousePressed
        // Solo borra si es exactamente el placeholder
        if (String.valueOf(contrasenaTxt.getPassword()).equals("....")) {
            contrasenaTxt.setText("");
            contrasenaTxt.setForeground(Color.black);
        }
        if (usuarioTxt.getText().isEmpty()) {
            usuarioTxt.setText("Ingrese su nombre de usuario");
            usuarioTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_contrasenaTxtMousePressed


    private void contrasenaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaTxtActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        xMause = evt.getX();
        yMause = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMause, y - yMause);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_salirMouseClicked

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        salir.setForeground(Color.RED);
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salir.setForeground(Color.WHITE);
    }//GEN-LAST:event_salirMouseExited

    private void ingresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseEntered
        ingresar.setBackground(new Color(72, 72, 72));
    }//GEN-LAST:event_ingresarMouseEntered

    private void ingresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseExited
        ingresar.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_ingresarMouseExited

    private void usuarioTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioTxtMouseClicked
        usuarioTxt.setText("");
//        usuarioTxt.setForeground(new Color(131,131,131));

    }//GEN-LAST:event_usuarioTxtMouseClicked

    private void contrasenaTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrasenaTxtMouseClicked
        contrasenaTxt.setText("");
        contrasenaTxt.setForeground(Color.black);
    }//GEN-LAST:event_contrasenaTxtMouseClicked

    private void ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseClicked
        this.Login();

        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarMouseClicked

    private void usuarioTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioTxtKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            contrasenaTxt.requestFocus();
        }


    }//GEN-LAST:event_usuarioTxtKeyPressed

    private void contrasenaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contrasenaTxtKeyPressed
        
        contrasenaTxt.setForeground(Color.black);
        if (evt.getKeyCode() == evt.VK_ENTER) {
            Login();
        }
    }//GEN-LAST:event_contrasenaTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contrasenaTxt;
    private javax.swing.JPanel ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel salir;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
    private void Login() {
        if (!usuarioTxt.getText().isEmpty() && !contrasenaTxt.getText().isEmpty()) {
            ControladorUsuario controlUsuario = new ControladorUsuario();
            Usuario usuario = new Usuario();
            usuario.setUsuario(usuarioTxt.getText().trim());
            usuario.setPassword(contrasenaTxt.getText().trim());
            if (controlUsuario.loginUser(usuario)) {
                //JOptionPane.showMessageDialog(null, "login correcto");
                FrmMenu menu=new FrmMenu();//crea un FrmMenu para poder trabajr 
                menu.setVisible(true);//esto hace que la ventana de menu aparesca 
                this.dispose();//esto hace que nuestro FrmLogin se oculte y se trabaje en el FrmMenu
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o Clave Incorrectos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese sus Credenciales");
        }
    }

}
