package vista;

import conexion.Conexion;
import controlador.ControladorCliente;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

public class InterGestionarClientes extends javax.swing.JInternalFrame {

    private int idCliente;

    public InterGestionarClientes() {
        initComponents();
//        this.setSize(1182, 607);
        this.setSize(new Dimension(1182, 607));
        this.setTitle("Gestionar Clientes");
        this.cargarTablaClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        botonEliminar = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(221, 240, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestionar Clientes");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 190, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaClientes.setBackground(new java.awt.Color(221, 240, 254));
        tablaClientes.setFont(new java.awt.Font("Roboto Condensed", 0, 24)); // NOI18N
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 290));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1150, 290));

        jPanel4.setBackground(new java.awt.Color(221, 240, 254));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(221, 240, 254));
        jLabel2.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cedula.png"))); // NOI18N
        jLabel2.setText("Cedula: ");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 90, 40));

        jLabel3.setBackground(new java.awt.Color(221, 240, 254));
        jLabel3.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nombreetiqueta.png"))); // NOI18N
        jLabel3.setText("Nombre: ");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 40));

        jLabel4.setBackground(new java.awt.Color(221, 240, 254));
        jLabel4.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nombreetiqueta.png"))); // NOI18N
        jLabel4.setText("Apellido: ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 100, 40));

        jLabel5.setBackground(new java.awt.Color(221, 240, 254));
        jLabel5.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/directorio-telefonico (1).png"))); // NOI18N
        jLabel5.setText("Telefono: ");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 40));

        jLabel6.setBackground(new java.awt.Color(221, 240, 254));
        jLabel6.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/direcciones (1).png"))); // NOI18N
        jLabel6.setText("Direccion: ");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 110, 40));

        txtApellido.setBackground(new java.awt.Color(221, 240, 254));
        txtApellido.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(51, 51, 51));
        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreMouseEntered(evt);
            }
        });
        jPanel4.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 210, 30));

        txtCedula.setBackground(new java.awt.Color(221, 240, 254));
        txtCedula.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(51, 51, 51));
        txtCedula.setBorder(null);
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreMouseEntered(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPanel4.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 210, 30));

        txtNombre.setBackground(new java.awt.Color(221, 240, 254));
        txtNombre.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreMouseEntered(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 210, 30));

        txtTelefono.setBackground(new java.awt.Color(221, 240, 254));
        txtTelefono.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(51, 51, 51));
        txtTelefono.setBorder(null);
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreMouseEntered(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel4.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 210, 30));

        txtDireccion.setBackground(new java.awt.Color(221, 240, 254));
        txtDireccion.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(51, 51, 51));
        txtDireccion.setBorder(null);
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtNombreMouseEntered(evt);
            }
        });
        jPanel4.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 210, 30));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 210, 30));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 210, 30));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 210, 30));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 210, 30));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 210, 30));

        botonEliminar.setBackground(new java.awt.Color(255, 153, 51));
        botonEliminar.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 14)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(0, 0, 0));
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar..png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jPanel4.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 120, 40));

        botonActualizar.setBackground(new java.awt.Color(0, 153, 255));
        botonActualizar.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 14)); // NOI18N
        botonActualizar.setForeground(new java.awt.Color(0, 0, 0));
        botonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizarCategoria.png"))); // NOI18N
        botonActualizar.setText("Actualizar");
        botonActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(botonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 120, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 1150, 220));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        Cliente cliente = new Cliente();
        ControladorCliente controlcliente = new ControladorCliente();

        if (txtNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete el campo:nombre del Cliente");
            txtNombre.setBackground(Color.RED);
            txtNombre.requestFocus();
            return;
        }

        if (txtApellido.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el Apellido del Cliente");
            txtApellido.setBackground(Color.RED);
            txtApellido.requestFocus();
            return;
        }

        if (txtCedula.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el numero de Cedula");
            txtCedula.setBackground(Color.RED);
            txtCedula.requestFocus();
            return;
        }
        if (txtTelefono.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el numero del contacto telefonico");
            txtTelefono.setBackground(Color.RED);
            txtTelefono.requestFocus();
            return;
        }

        try {
            // Establecer detalles del producto
            cliente.setNombre(txtNombre.getText().trim());
            cliente.setApellido(txtApellido.getText().trim());
            cliente.setCedula(txtCedula.getText().trim());
            cliente.setTelefono(txtTelefono.getText().trim());
            cliente.setDireccion(txtDireccion.getText().trim());
            cliente.setEstado(1);

            //Guardar Producto
            if (controlcliente.actualizar(cliente, idCliente)) {
                JOptionPane.showMessageDialog(null, "Registro actualizado");
                this.limpiar();
                this.cargarTablaClientes();
                idCliente = 0;

            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar el Cliente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error al guardar el Cliente: " + e.getMessage());
        }

    }//GEN-LAST:event_botonActualizarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        txtTelefono.setBackground(new Color(221, 240, 254));
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed

        ControladorCliente controlCliente = new ControladorCliente();
        this.limpiar();
        if (idCliente == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un Cliente");
            return;
        } else {
            int confirm = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el Cliente?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                if (controlCliente.eliminar(idCliente)) {
                    JOptionPane.showMessageDialog(null, "Cliente Eliminado");
                    this.cargarTablaClientes();
                    this.limpiar();

                } else {
                    JOptionPane.showMessageDialog(null, "Error al Eliminar el Cliente");
                }
            }
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void txtNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseEntered
        txtNombre.setBackground(new Color(221, 240, 254));
    }//GEN-LAST:event_txtNombreMouseEntered

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        txtCedula.setBackground(new Color(221, 240, 254));
    }//GEN-LAST:event_txtCedulaActionPerformed
    private void txtApellidoEntered(java.awt.event.MouseEvent evt) {
        txtApellido.setBackground(new Color(221, 240, 254));
    }

    private void txtTelefonoEntered(java.awt.event.MouseEvent evt) {
        txtTelefono.setBackground(new Color(221, 240, 254));
    }

    private void txtDireccionMouseEntered(java.awt.event.MouseEvent evt) {
        txtDireccion.setBackground(new Color(221, 240, 254));
    }

    private void txtCedulaMouseEntered(java.awt.event.MouseEvent evt) {
        txtApellido.setBackground(new Color(221, 240, 254));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public static javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
    private void cargarTablaClientes() {
        this.limpiar();
        Connection con = conexion.Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "SELECT * FROM tb_cliente;";
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            InterGestionarClientes.tablaClientes = new JTable(model);
            InterGestionarClientes.jScrollPane1.setViewportView(InterGestionarClientes.tablaClientes);
            model.addColumn("N°");
            model.addColumn("Nombre");
            model.addColumn("Apellido");
            model.addColumn("Cedula");
            model.addColumn("Telefono");
            model.addColumn("Direccion");
            model.addColumn("Estado");
            while (rs.next()) {
                Object fila[] = new Object[7];
                for (int i = 0; i < 7; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al llenar la tabla clientes " + e);
        }
        InterGestionarClientes.tablaClientes.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                int filaPoint = InterGestionarClientes.tablaClientes.rowAtPoint(e.getPoint());
                int columnaPoint = 0;
                if (filaPoint > -1) {
                    idCliente = (int) model.getValueAt(filaPoint, columnaPoint);
                    EnviarDatosClienteSeleccionado(idCliente);
                }

            }
        });
    }

    private void limpiar() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        txtCedula.setText("");
    }

    public void EnviarDatosClienteSeleccionado(int idCliente) {
        this.limpiar();
        try {
            Connection con = Conexion.conectar();
            PreparedStatement pst = con.prepareStatement(
                    "select * from tb_cliente where idCliente= '" + idCliente + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                txtNombre.setText(rs.getString("nombre"));
                txtApellido.setText(rs.getString("apellido"));
                txtCedula.setText(rs.getString("cedula"));
                txtTelefono.setText(rs.getString("telefono"));
                txtDireccion.setText(rs.getString("direccion"));
                idCliente = 0;
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al seleccionar cliente" + e.getMessage());
        }
    }

}
