package vista;

import conexion.Conexion;
import controlador.PdfReparacion;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class InterGestionarReparacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterGestionarReparacion
     */
    public InterGestionarReparacion() {
        initComponents();
        this.configurarTabla();
        this.cargarReparaciones();

        // Evento: cuando seleccionas una fila de la tabla
        jTableReparaciones.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = jTableReparaciones.getSelectedRow();
                if (fila >= 0) {
                    int idReparacion = (int) jTableReparaciones.getValueAt(fila, 0);
                    EnviarDatosReparacionSeleccionado(idReparacion);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReparaciones = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botonActualizar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        totalPagarReparacion1 = new javax.swing.JTextField();
        botonVerPdf = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(221, 240, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableReparaciones.setBackground(new java.awt.Color(221, 240, 254));
        jTableReparaciones.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jTableReparaciones.setForeground(new java.awt.Color(0, 0, 0));
        jTableReparaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableReparaciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1420, 140));

        txtAreaDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setRows(5);
        txtAreaDescripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(txtAreaDescripcion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 720, 370));

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreCliente.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombreCliente.setEnabled(false);
        txtNombreCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreClienteMouseClicked(evt);
            }
        });
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, 490, 30));

        jLabel4.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre Cliente: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 150, 30));

        botonActualizar.setBackground(new java.awt.Color(51, 102, 255));
        botonActualizar.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        botonActualizar.setForeground(new java.awt.Color(0, 0, 0));
        botonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizarCategoria.png"))); // NOI18N
        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(botonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 130, 30));

        botonEliminar.setBackground(new java.awt.Color(255, 102, 102));
        botonEliminar.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(0, 0, 0));
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar..png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 460, 130, 30));

        jLabel5.setFont(new java.awt.Font("Roboto Condensed Medium", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Valor Reparacion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 150, 30));

        totalPagarReparacion1.setEditable(false);
        totalPagarReparacion1.setBackground(new java.awt.Color(255, 255, 255));
        totalPagarReparacion1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        totalPagarReparacion1.setForeground(new java.awt.Color(0, 0, 0));
        totalPagarReparacion1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        totalPagarReparacion1.setEnabled(false);
        totalPagarReparacion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalPagarReparacion1MouseClicked(evt);
            }
        });
        totalPagarReparacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPagarReparacion1ActionPerformed(evt);
            }
        });
        jPanel1.add(totalPagarReparacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 290, 30));

        botonVerPdf.setBackground(new java.awt.Color(255, 255, 102));
        botonVerPdf.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        botonVerPdf.setForeground(new java.awt.Color(0, 0, 0));
        botonVerPdf.setText("Ver PDF");
        botonVerPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerPdfActionPerformed(evt);
            }
        });
        jPanel1.add(botonVerPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreClienteMouseClicked

    }//GEN-LAST:event_txtNombreClienteMouseClicked

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void totalPagarReparacion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalPagarReparacion1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPagarReparacion1MouseClicked

    private void totalPagarReparacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPagarReparacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPagarReparacion1ActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        
         int idReparacion = obtenerIdReparacionSeleccionada();
    if (idReparacion == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una reparación para actualizar.");
        return;
    }

    String descripcion = txtAreaDescripcion.getText().trim();
    String precio = totalPagarReparacion1.getText().trim();

    if (descripcion.isEmpty() || precio.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar la descripción y el precio.");
        return;
    }

    try (Connection con = Conexion.conectar()) {
        String sql = "UPDATE tb_reparacion SET descripcion=?, precioReparacion=? WHERE idReparacion=?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, descripcion);
        ps.setDouble(2, Double.parseDouble(precio));
        ps.setInt(3, idReparacion);

        int filas = ps.executeUpdate();
        if (filas > 0) {
            JOptionPane.showMessageDialog(this, "Reparación actualizada correctamente.");
            cargarReparaciones(); // refrescar tabla
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar la reparación.");
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al actualizar: " + ex.getMessage());
    }
        
        
//        botonEliminar.addActionListener(e -> {
//            int idReparacion = obtenerIdReparacionSeleccionada();
//            if (idReparacion == -1) {
//                JOptionPane.showMessageDialog(this, "Seleccione una reparación de la tabla.");
//                return;
//            }
//
//            int confirm = JOptionPane.showConfirmDialog(this,
//                    "¿Seguro que desea eliminar esta reparación?",
//                    "Confirmar Eliminación",
//                    JOptionPane.YES_NO_OPTION
//            );
//
//            if (confirm == JOptionPane.YES_OPTION) {
//                try {
//                    Connection con = Conexion.conectar();
//                    PreparedStatement pst = con.prepareStatement(
//                            "DELETE FROM tb_reparacion WHERE idReparacion = ?"
//                    );
//                    pst.setInt(1, idReparacion);
//
//                    int rows = pst.executeUpdate();
//                    con.close();
//
//                    if (rows > 0) {
//                        JOptionPane.showMessageDialog(this, "Reparación eliminada correctamente.");
//                        refrescarTabla();
//                        limpiar();
//                    }
//                } catch (SQLException ex) {
//                    JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage());
//                }
//            }
//            limpiar();
//        });
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonVerPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerPdfActionPerformed
      int idReparacion = obtenerIdReparacionSeleccionada();
    if (idReparacion == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una reparación para generar el PDF.");
        return;
    }

    try {
        PdfReparacion pdf = new PdfReparacion();
        pdf.generarPdf(idReparacion); // tu método ya existente
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al generar PDF: " + ex.getMessage());
    }
        
//        botonVerPdf.addActionListener(e -> {
//            limpiar();
//            int idReparacion = obtenerIdReparacionSeleccionada();
//            if (idReparacion == -1) {
//                JOptionPane.showMessageDialog(this, "Seleccione una reparación para generar el PDF.");
//                return;
//            }
//
//            try {
//                PdfReparacion pdf = new PdfReparacion();
//                pdf.generarPdf(idReparacion); // método que ya debes tener en tu clase PdfReparacion
//            } catch (Exception ex) {
//                JOptionPane.showMessageDialog(this, "Error al generar PDF: " + ex.getMessage());
//            }
//
//        });
    }//GEN-LAST:event_botonVerPdfActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        int idReparacion = obtenerIdReparacionSeleccionada();
        if (idReparacion == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una reparación para eliminar.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar la reparación seleccionada?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection con = Conexion.conectar()) {
                String sql = "DELETE FROM tb_reparacion WHERE idReparacion = ?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1, idReparacion);
                int filasAfectadas = ps.executeUpdate();

                if (filasAfectadas > 0) {
                    JOptionPane.showMessageDialog(this, "Reparación eliminada con éxito.");
                    refrescarTabla(); // recarga datos
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar la reparación.");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage());
            }
        }

//        limpiar();
//        botonEliminar.addActionListener(e -> {
//            int idReparacion = obtenerIdReparacionSeleccionada(); // tu método para sacar el ID
//            if (idReparacion == -1) {
//                JOptionPane.showMessageDialog(this, "Seleccione una reparación para eliminar.");
//                return;
//            }
//
//            int confirm = JOptionPane.showConfirmDialog(this,
//                    "¿Está seguro de eliminar la reparación seleccionada?",
//                    "Confirmar eliminación",
//                    JOptionPane.YES_NO_OPTION);
//
//            if (confirm == JOptionPane.YES_OPTION) {
//                try (Connection con = Conexion.conectar()) {
//                    String sql = "DELETE FROM tb_reparacion WHERE idReparacion = ?";
//                    PreparedStatement ps = con.prepareStatement(sql);
//                    ps.setInt(1, idReparacion);
//                    int filasAfectadas = ps.executeUpdate();
//
//                    if (filasAfectadas > 0) {
//                        JOptionPane.showMessageDialog(this, "Reparación eliminada con éxito.");
//                        cargarReparaciones(); // 🔹 método tuyo para refrescar la tabla
//                    } else {
//                        JOptionPane.showMessageDialog(this, "No se pudo eliminar la reparación.");
//                    }
//                } catch (Exception ex) {
//                    JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage());
//                }
//            }
//        });
    }//GEN-LAST:event_botonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonVerPdf;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTableReparaciones;
    public javax.swing.JTextField totalPagarReparacion1;
    private javax.swing.JTextArea txtAreaDescripcion;
    public javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
    private void configurarTabla() {
        // Crear el modelo de la tabla con las columnas específicas
        DefaultTableModel model = new DefaultTableModel();

        // Definir las columnas
        model.addColumn("N°");
        model.addColumn("Fecha");
        model.addColumn("Cliente");
        model.addColumn("Precio");
        model.addColumn("Descripción");

        // Asignar el modelo a la tabla
        jTableReparaciones.setModel(model);

        // Hacer que la tabla no sea editable
        jTableReparaciones.setDefaultEditor(Object.class, null);

        // Ajustar el ancho de las columnas
        ajustarAnchoColumnas();
    }

    private void cargarReparaciones() {
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            System.out.println("Iniciando carga de reparaciones...");
            con = Conexion.conectar();

            if (con == null) {
                System.out.println("Error: Conexión es null");
                JOptionPane.showMessageDialog(this, "Error: No se pudo conectar a la base de datos");
                return;
            }

            System.out.println("Conexión establecida correctamente");

            // Obtener el modelo de la tabla
            DefaultTableModel model = (DefaultTableModel) jTableReparaciones.getModel();

            // Limpiar filas existentes
            model.setRowCount(0);
            System.out.println("Tabla limpiada, columnas: " + model.getColumnCount());

            // Query para obtener reparaciones con datos del cliente
            String sql = "SELECT r.idReparacion, r.fechaReparacion, r.precioReparacion, r.descripcion, "
                    + "CONCAT(c.nombre, ' ', c.apellido) AS nombreCompleto "
                    + "FROM tb_reparacion r "
                    + "INNER JOIN tb_cliente c ON r.idCliente = c.idCliente "
                    + "ORDER BY r.idReparacion DESC";

            System.out.println("Ejecutando consulta: " + sql);
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            int contador = 0;
            // Llenar la tabla with los datos
            while (rs.next()) {
                Object[] fila = new Object[5];
                fila[0] = rs.getInt("idReparacion");
                fila[1] = rs.getDate("fechaReparacion");
                fila[2] = rs.getString("nombreCompleto");
                fila[3] = String.format("$%.2f", rs.getDouble("precioReparacion"));
                fila[4] = rs.getString("descripcion");

                model.addRow(fila);
                contador++;
                System.out.println("Fila agregada: " + contador + " - ID: " + fila[0]);
            }

            System.out.println("Total de reparaciones cargadas: " + contador);

            // Mensaje informativo si no hay datos
            if (model.getRowCount() == 0) {
                System.out.println("No se encontraron reparaciones");
                JOptionPane.showMessageDialog(this, "No se encontraron reparaciones registradas.\n"
                        + "Verifica que existan registros en las tablas tb_reparacion y tb_cliente.");
            } else {
                System.out.println("Reparaciones cargadas exitosamente en la tabla");
            }

        } catch (SQLException e) {
            System.out.println("Error SQL: " + e.getMessage());
            System.out.println("Código de error: " + e.getErrorCode());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al cargar las reparaciones:\n" + e.getMessage()
                    + "\nCódigo: " + e.getErrorCode(),
                    "Error de Base de Datos",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            // Cerrar recursos
            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                if (con != null) {
                    con.close();
                }
                System.out.println("Recursos cerrados correctamente");
            } catch (SQLException e) {
                System.out.println("Error al cerrar recursos: " + e.getMessage());
            }
        }
    }

    private void ajustarAnchoColumnas() {
        // Verificar que la tabla tenga columnas
        if (jTableReparaciones.getColumnCount() > 0) {
            // Ajustar el ancho de las columnas para mejor visualización
            jTableReparaciones.getColumnModel().getColumn(0).setPreferredWidth(50);  // N°
            jTableReparaciones.getColumnModel().getColumn(1).setPreferredWidth(120); // Fecha
            jTableReparaciones.getColumnModel().getColumn(2).setPreferredWidth(200); // Cliente
            jTableReparaciones.getColumnModel().getColumn(3).setPreferredWidth(120); // Precio
            jTableReparaciones.getColumnModel().getColumn(4).setPreferredWidth(400); // Descripción
        }
    }

    // Método para refrescar la tabla
    public void refrescarTabla() {
        cargarReparaciones();
    }

    // Método para obtener el ID de la reparación seleccionada
    public int obtenerIdReparacionSeleccionada() {
        int filaSeleccionada = jTableReparaciones.getSelectedRow();
        if (filaSeleccionada >= 0) {
            return (int) jTableReparaciones.getValueAt(filaSeleccionada, 0);
        }
        return -1;
    }

    public void EnviarDatosReparacionSeleccionado(int idReparacion) {
        this.limpiar();
        try {
            Connection con = Conexion.conectar();
            PreparedStatement pst = con.prepareStatement(
                    "SELECT r.descripcion, r.precioReparacion, r.idCliente, "
                    + "CONCAT(c.nombre, ' ', c.apellido) AS nombreCompleto "
                    + "FROM tb_reparacion r "
                    + "INNER JOIN tb_cliente c ON r.idCliente = c.idCliente "
                    + "WHERE r.idReparacion = ?"
            );
            pst.setInt(1, idReparacion);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txtAreaDescripcion.setText(rs.getString("descripcion"));
                totalPagarReparacion1.setText(rs.getString("precioReparacion"));
                txtNombreCliente.setText(rs.getString("nombreCompleto"));
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al seleccionar reparación: " + e.getMessage());
        }
    }

    private void limpiar() {
        txtAreaDescripcion.setText("");
        totalPagarReparacion1.setText("");
        txtNombreCliente.setText("");

    }

    public void EnviarDatosCliente(int idCliente) {
        this.limpiar();
        try {
            Connection con = Conexion.conectar();
            PreparedStatement pst = con.prepareStatement(
                    "select * from tb_cliente where idCliente= '" + idCliente + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                txtNombreCliente.setText(rs.getString("nombre") + " " + rs.getString("apellido"));
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al seleccionar cliente" + e.getMessage());
        }
    }
}
